[build]
  # Diretório base onde seu projeto está localizado
  base = ""
  
  # Comando de build
  command = "npm install && npm install --prefix client && npm run build --prefix client"
  
  # Diretório onde os arquivos estáticos serão publicados
  publish = "client/dist"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200